# Generated by `nixos-generate-config --show-hardware-config`, then edited.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Single SATA disk, no encryption: sda1 root, sda2 swap.
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6978eaac-baf1-4aeb-9a2f-cc7feb7b4e09";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/55ed45e4-7e79-48ad-9064-b923f56fd9e2"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
