# Generated by `nixos-generate-config --show-hardware-config`, then edited.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # p2 holds the root filesystem, p3 swap.
  boot.initrd.luks.devices = {
    "luks-74bd5c82-6749-4ec9-9f4a-7e45299a334d".device =
      "/dev/disk/by-uuid/74bd5c82-6749-4ec9-9f4a-7e45299a334d";
    "luks-413dddc4-3e89-4ffc-b975-82f062435680".device =
      "/dev/disk/by-uuid/413dddc4-3e89-4ffc-b975-82f062435680";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af6ee93b-0c11-49cf-ae18-343d66a546db";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6604-ADD5";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a6c1d70c-9713-44c5-a0a1-9a5b4eacf482"; }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
