# Auto-generated using compose2nix v0.3.1.
{
  config,
  pkgs,
  lib,
  ...
}:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."gitea-db" = {
    image = "postgres:14";
    environment = {
      "POSTGRES_DB" = "gitea";
      "POSTGRES_PASSWORD" = "rand0m";
      "POSTGRES_USER" = "gitea";
    };
    volumes = [
      "gitea_gitea-db:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gitea-db"
      "--network=gitea_default"
    ];
  };
  systemd.services."docker-gitea-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gitea_default.service"
      "docker-volume-gitea_gitea-db.service"
    ];
    requires = [
      "docker-network-gitea_default.service"
      "docker-volume-gitea_gitea-db.service"
    ];
    partOf = [
      "docker-compose-gitea-root.target"
    ];
    wantedBy = [
      "docker-compose-gitea-root.target"
    ];
  };
  virtualisation.oci-containers.containers."gitea-server" = {
    image = "gitea/gitea:1.23.3";
    environment = {
      "GITEA__database__DB_TYPE" = "postgres";
      "GITEA__database__HOST" = "gitea-db:5432";
      "GITEA__database__NAME" = "gitea";
      "GITEA__database__PASSWD" = "rand0m";
      "GITEA__database__USER" = "gitea";
      "USER_GID" = "1000";
      "USER_UID" = "1000";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/etc/timezone:/etc/timezone:ro"
      "gitea_gitea-data:/data:rw"
    ];
    ports = [
      "3000:3000/tcp"
      "2222:2222/tcp"
    ];
    dependsOn = [
      "gitea-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gitea-server"
      "--network=gitea_default"
    ];
  };
  systemd.services."docker-gitea-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-gitea_default.service"
      "docker-volume-gitea_gitea-data.service"
    ];
    requires = [
      "docker-network-gitea_default.service"
      "docker-volume-gitea_gitea-data.service"
    ];
    partOf = [
      "docker-compose-gitea-root.target"
    ];
    wantedBy = [
      "docker-compose-gitea-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-gitea_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f gitea_default";
    };
    script = ''
      docker network inspect gitea_default || docker network create gitea_default
    '';
    partOf = [ "docker-compose-gitea-root.target" ];
    wantedBy = [ "docker-compose-gitea-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-gitea_gitea-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect gitea_gitea-data || docker volume create gitea_gitea-data --driver=local
    '';
    partOf = [ "docker-compose-gitea-root.target" ];
    wantedBy = [ "docker-compose-gitea-root.target" ];
  };
  systemd.services."docker-volume-gitea_gitea-db" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect gitea_gitea-db || docker volume create gitea_gitea-db --driver=local
    '';
    partOf = [ "docker-compose-gitea-root.target" ];
    wantedBy = [ "docker-compose-gitea-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-gitea-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
